Polish translation for LAMBS Danger
nk3nny/LambsDanger pull request #162
Opened 2020-09-17 02:55 UTC by MiszczuZPolski

I saw that you needed help with the translation into Polish, so I decided that I would help.

2020-09-17 13:16 UTC, veteran29 requested changes

2020-09-17 13:16 UTC, veteran29 commented on addons/danger/stringtable.xml
> +            <Polish>Przełącza zwiększony zasięg komunikacji dla tego urządzenia</Polish>
```suggestion
            <Polish>Przełącza zwiększony zasięg komunikacji dla tej jednostki</Polish>
```

2020-09-17 13:16 UTC, veteran29 commented on addons/danger/stringtable.xml
> +            <Polish>Jednostka z włączonym radiem ma zwiększony zasięg komunikacji podczas przekazywania informacji \n Ten efekt może być również osiągnięty, poprzez wyekwipowanie jednostki w plecak z
```suggestion
            <Polish>Jednostka z włączonym radiem ma zwiększony zasięg komunikacji podczas przekazywania informacji \n Ten efekt może być również osiągnięty, poprzez wyekwipowanie jednostki w plecak z radiem lub plecak kompatybilny z modem TFAR</Polish>
```

2020-09-17 13:16 UTC, veteran29 commented on addons/danger/stringtable.xml
> +            <Polish>Obszar na którym sojusznicze jednostki dołączą do walki. Jednostki w trybie walki będą szukały osłony i kierować się w stronę najbliższego znanego zagrożenia.</Polish>
```suggestion
            <Polish>Obszar na którym sojusznicze jednostki dołączą do walki. Jednostki w trybie walki będą szukały osłony i kierowały się w stronę najbliższego znanego zagrożenia.</Polish>
```

2020-09-17 13:16 UTC, veteran29 commented on addons/danger/stringtable.xml
> +            <Polish>Maksymalna wartość „knowAbout” dzielona między jednostki. \n Ustawienie tej wartości większej niż 1 może spowodować, że odlegli sojusznicy przejdą w tryb zagrożenia.</Polish>
```suggestion
            <Polish>Maksymalna wartość "knowsAbout" dzielona między jednostki. \n Ustawienie tej wartości większej niż 1 może spowodować, że odlegli sojusznicy przejdą w tryb zagrożenia.</Polish>
```

2020-09-17 13:16 UTC, veteran29 commented on addons/eventhandlers/stringtable.xml
> +            <Polish>Licznik czasu resetowania modułu obsługi zdarzenia wybuchu</Polish>
```suggestion
            <Polish>Czas resetowania reakcji na zdarzenie wybuchu</Polish>
```

2020-09-17 13:16 UTC, veteran29 commented on addons/eventhandlers/stringtable.xml
> +            <Polish>Konfiguruje czas resetowania wybuchu</Polish>
```suggestion
            <Polish>Konfiguruje czas resetowania reakcji na zdarzenie wybuchu.</Polish>
```

2020-09-17 13:41 UTC, diwako commented
Here is me, pretending to understand all of this. Keep it up :D

2020-09-17 16:23 UTC, veteran29 requested changes

2020-09-17 17:54 UTC, MiszczuZPolski commented on addons/danger/stringtable.xml
> +            <Polish>Wyłącz SI dla jednostek</Polish>
Ok, no problem

2020-09-19 17:22 UTC, veteran29 requested changes

2020-09-19 17:22 UTC, veteran29 commented on addons/main/stringtable.xml
> +            <Polish>Wyłącz połączenia</Polish>
```suggestion
            <Polish>Wyłącz okrzyki</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/main/stringtable.xml
> +            <Polish>Wyłącza dodatkowe wywołania od jednostek w zależności od sytuacji</Polish>
```suggestion
            <Polish>Wyłącza dodatkowe wołania/okrzyki jednostek w zależności od sytuacji</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Gdy dynamiczne centrum jest widoczne, jest możliwe, żeby poruszać zasięgiem zadania.</Polish>
```suggestion
            <Polish>Gdy dynamiczne centrum jest widoczne, jest możliwe, żeby poruszać centralnym punktem przeszukiwania budynku.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Task - Zasadzka</Polish>
```suggestion
            <Polish>Zadanie - Zasadzka</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Task - Reset</Polish>
```suggestion
            <Polish>Zadanie - Reset</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Zadanie - Zasadzka pozwala jednostkom przeprowadzenie zasadzki na przeciwników. Grupa będzie używać osłon i trzymać się nisko w celu utrzymania anonimowości.</Polish>
```suggestion
            <Polish>Zadanie - Zasadzka pozwala jednostkom przeprowadzenie zasadzki na przeciwników. Grupa będzie używać osłon i trzymać się nisko w celu uniknięcia wykrycia.&lt;br/&gt;&lt;br/&gt;Domyślnie moduł wyszukuje tylko wrogich graczy.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Obszar na którym grupa będzie szukać przeciwników. \n Domyślnie, moduł jest stworzony aby używać go przeciwko wrogim graczom.</Polish>
```suggestion
            <Polish>Obszar na którym grupa będzie szukać przeciwników. \n Domyślnie moduł wyszukuje tylko wrogich graczy.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Zadanie - Polowanie sprawia, że jednostki patrolują obszar określony przez moduł. Grupa podchodzi do celu spiralnie i spokojnie. Jednostka użyje latarek jeśli będzie to możliwe. &
```suggestion
            <Polish>Zadanie - Polowanie sprawia, że jednostki patrolują obszar określony przez moduł. Grupa podchodzi do celu spiralnie i spokojnie. Jednostka użyje latarek jeśli będzie to możliwe.&lt;br/&gt; &lt;br/&gt;Domyślnie moduł wyszukuje tylko wrogich graczy.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą mniej celne. \n Domyślnie 70 sekund</Polish>
```suggestion
            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą mniej celne.\nDomyślnie 70 sekund</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Obszar na którym grupa będzie szukać przeciwników. \n Domyślnie, moduł jest stworzony aby używać go przeciwko wrogim graczom.</Polish>
```suggestion
            <Polish>Obszar na którym grupa będzie szukać przeciwników.\nDomyślnie moduł wyszukuje tylko wrogich graczy.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Zadanie - Szturm sprawia, że jednostki agresywnie szturmują naprzeciw wrogom. Jednostki będą poruszać się bardzo agresywnie, często ignorując osłonę i ogień zaporowy.&lt;br/&gt;&l
```suggestion
            <Polish>Zadanie - Szturm sprawia, że jednostki agresywnie szturmują naprzeciw wrogom. Jednostki będą poruszać się bardzo agresywnie, często ignorując osłonę i ogień zaporowy.&lt;br/&gt;&lt;br/&gt;Domyślnie moduł wyszukuje tylko wrogich graczy. Wyłącz FSM dla jednostek, dla prawdziwie przerażających przeciwników.</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą mniej celne. \n Domyślnie 4 sekund</Polish>
```suggestion
            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą mniej celne.\nDomyślnie 4 sekund</Polish>
```

2020-09-19 17:22 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Określa na jaką jednostkę ma zadziałać skrypt. \n Lista jest sortowana po dystansie.</Polish>
```suggestion
            <Polish>Określa na jaką jednostkę ma zadziałać skrypt.\nLista jest sortowana po dystansie.</Polish>
```

2020-10-06 15:06 UTC, jokoho48 commented
@veteran29 @MiszczuZPolski status?

2020-10-06 15:12 UTC, veteran29 requested changes

2020-10-06 15:12 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Włącz tę opcję, aby nie wystrzelić strzałów korygujących, używanych przez kontrolera do skorygowania ostrzału na punkt</Polish>
```suggestion
            <Polish>Włącz tę opcję, aby nie wystrzelić strzałów korygujących, używanych przez kontrolera do skorygowania ostrzału na punkt.\nWłączenie tej opcji spowoduje natychmiastowy ostrzał na wyznaczony cel.</Polish>
```

2020-10-06 15:12 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Usuwa moduł podczas uruchamiania. \nJeśli opcja nie jest aktywowana, można przemieścić moduł w celu dynamicznego dostosowywania lokalizacji docelowej.</Polish>
```suggestion
            <Polish>Usuwa moduł podczas uruchamiania.\nJeśli opcja nie jest aktywowana, można przemieścić moduł w celu dynamicznego dostosowywania lokalizacji docelowej.</Polish>
```

2020-10-06 15:12 UTC, veteran29 commented on addons/wp/stringtable.xml
> +            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą przeszukiwać budynki bardziej ostrożnie. \nDomyślnie 21 sekund</Polish>
```suggestion
            <Polish>Czas cyklu skryptu w sekundach. Wyższy czas sprawi, że jednostki będą przeszukiwać budynki bardziej ostrożnie.\nDomyślnie 21 sekund</Polish>
```

2020-10-13 21:42 UTC, veteran29 approved these changes

2020-10-13 21:45 UTC, merged