Adds teleport option to taskPatrol
nk3nny/LambsDanger pull request #428
Opened 2024-11-23 17:40 UTC by nk3nny

Extends Modules (Zeus and Eden) with a teleport option in taskPatrol.  When enabled, it functions much like Garrisons-- placing the group at at a randomly selected position with the patrol area.

2024-11-23 17:52 UTC, jokoho48 commented on addons/wp/functions/Modules/fnc_modulePatrol.sqf
> +                        [LSTRING(Module_TaskGarrison_Teleport_DisplayName), "BOOLEAN", LSTRING(Module_TaskGarrison_Teleport_Tooltip), TASK_PATROL_TELEPORT]
When we use it in multiple places, we should remove the Garrison from the name

2024-11-23 22:39 UTC, rautamiekka requested changes

2024-11-23 22:39 UTC, rautamiekka commented on addons/wp/functions/fnc_taskPatrol.sqf
> + * 7: Teleport group <BOOL>
This needs far better wording. The [comment](https://github.com/nk3nny/LambsDanger/pull/428/files#diff-a7c7c916574286f9ebceb75bd0d1ec5b509b333c885b6dc9b10c0d8b5ddc5840R123) for the associated code says it teleports the group to a random waypoint position, which itself is confusing cuz it means a random waypoint from the ones the group currently has.

2025-01-06 18:10 UTC, nk3nny commented on addons/wp/functions/Modules/fnc_modulePatrol.sqf
> +                        [LSTRING(Module_TaskGarrison_Teleport_DisplayName), "BOOLEAN", LSTRING(Module_TaskGarrison_Teleport_Tooltip), TASK_PATROL_TELEPORT]
Good call

2025-01-06 18:10 UTC, nk3nny commented on addons/wp/functions/fnc_taskPatrol.sqf
> + * 7: Teleport group <BOOL>
Good point!

2025-01-06 18:14 UTC, merged